# Server
server.error.whitelabel.enabled: false
# Spring actuator
management:
  endpoints:
    web:
      exposure:
        include: metrics,health
# Spring
spring:
  application:
    name: com.apnatime.friends_graph
  main:
    banner-mode: 'off'
  mvc:
    favicon:
      enabled: false
  jackson:
    time-zone: UTC
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    generator:
      write-numbers-as-strings: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    baselineOn-migrate: true
    ignoreMissingMigrations: true
    table: schema_version # for old version

  datasource:
    url: jdbc:${databaseServer}
    username: ${databaseUsername}
    password: ${databasePassword}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 600000 # 10 minutes
      idle-timeout: 300000 # current 5m
      leak-detection-threshold: 10000 # 10s
      maximum-pool-size: 60
      minimum-idle: 10

spring.flyway.baseline-on-migrate: true